# Generated by Django 3.0.3 on 2020-02-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=12, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
