# Generated by Django 3.0.3 on 2020-02-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40, unique=True, verbose_name='Student Name')),
                ('address', models.CharField(max_length=300)),
                ('slugs', models.SlugField(max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
    ]
