# Generated by Django 3.0.3 on 2020-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200221_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_no', models.IntegerField(verbose_name='Faculty No:')),
                ('Faculty_name', models.CharField(max_length=40, verbose_name='Faculty Name')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Contact No.')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('F_type', models.CharField(choices=[('principal', 'principal'), ('HOD', 'HOD'), ('professor', 'professor'), ('Assistant Professor', 'Assistant Professor')], max_length=30, verbose_name='Faculty Type')),
            ],
            options={
                'ordering': ['Faculty_name'],
            },
        ),
    ]
